# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_cardmanager_creditcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardManager',
        ),
    ]
