# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-06 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='tuskysclub@tuskysclub.com', max_length=75, unique=True),
        ),
    ]
