# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandsproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=599.99, max_digits=10),
        ),
    ]
