# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import wandsproducts.models


class Migration(migrations.Migration):

    dependencies = [
        ('wandsproducts', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=wandsproducts.models.upload_image_path),
        ),
    ]
