# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandsproducts', '0004_auto_20180510_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
