# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wandsproducts', '0008_auto_20180513_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
