# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-28 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailingpreferences',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
