# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-31 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0002_emailingpreferences_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailingpreferences',
            old_name='update',
            new_name='updated',
        ),
    ]
